name: CI/CD Tiem Hoa Tuoi

# Kịch bản chạy khi có code push vào nhánh main
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Lấy code mới nhất về máy ảo của GitHub
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Cài đặt môi trường Java 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # 3. Build & Test với Maven
    - name: Build with Maven
      env:
        DB_URL: ${{ secrets.DB_URL }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
        PAYPAL_CLIENT_SECRET: ${{ secrets.PAYPAL_CLIENT_SECRET }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      run: mvn clean package

    # 4. Đăng nhập vào Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: pinovn
        password: ${{ secrets.PINOVN }}

    # 5. Build Docker Image và Đẩy lên Docker Hub
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # Tên Image trên Docker Hub
        tags: pinovn/tiem-hoa-tuoi-backend:latest

    # 6. Báo cho Render biết để kéo Image mới về
    - name: Trigger Render Deploy
      run: curl "${{ secrets.RENDER_DEPLOY }}"