name: CI/CD Tiem Hoa Tuoi

# Kịch bản chạy khi có code push vào nhánh main
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Lấy code mới nhất về máy ảo của GitHub
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Cài đặt môi trường Java 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # 3. Chạy Unit Test với Maven
    - name: Run Unit Tests
      run: mvn test

    # 4. Đăng nhập vào Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: pinovn
        password: ${{ secrets.PINOVN }}

    # 5. Build Docker Image và Đẩy lên Docker Hub
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # Sửa 'tên_user_của_bro' thành tên thật trên Docker Hub nhé
        tags: pinovn/tiem-hoa-tuoi-backend:latest